### ISSUE TITLE
Installation process

### ISSUE THREAD

**Issue by Overdrivr** [matthew-brett/x86cpu#1]
Hi, 

I cannot install this module without Microsoft Visual Build tools. Is there a way to remove this requirement ? I would like to use this module into a self-check for tensorflow but would like to keep the dependencies small.

**Comment by matthew-brett** [comment]
What Python are you installing for?  I guess you don't get a wheel?

**Comment by Overdrivr** [comment]
Python 3.6.6, 64 bits

**Comment by matthew-brett** [comment]
I uploaded some new wheels, does it work now?

**Comment by Overdrivr** [comment]
It's working perfect, thanks !
